database:
  type: "sqlite"
  sqlite:
    path: "plugins/MysticRPG/database.db"
  mongo:
    connectionString: "mongodb://localhost:27017"
    databaseName: "xarumystic"

logging:
  debug: true

redis:
  enabled: true
  mockInMemory: true
  host: "localhost"
  port: 6379
  password: ""