# MysticRPG Configuration
database:
  type: sqlite # or sqlite
  mongo:
    connectionString: "mongodb://localhost:27017"
    databaseName: "xarumystic"
  sqlite:
    path: "plugins/MysticRPG/database.db"
discordBotToken: ""
discordGuildId: "1265708766100324415"