name: MysticRPG
version: 1.0.1
main: eu.xaru.mysticrpg.cores.MysticCore
author: Xaru
description: An RPG plugin to bring a mystical adventure to Minecraft.
api-version: 1.13
depend: [LuckPerms, ModelEngine]
commands: